import type { WorkspaceState } from "@/types/workspace";

const now = new Date().toISOString();

export const defaultWorkspaceState: WorkspaceState = {
  skillMap: {
    tools: "ChatGPT, Codex, n8n, automações, HeyGen",
    knowledge: "Prompts, análise de documentos, atendimento, conteúdo, fluxos comerciais",
    experiences: "",
    processes: "Responder perguntas frequentes, qualificar leads, organizar documentos, gerar propostas",
    problems: "Demora no atendimento, retrabalho, informações espalhadas, leads esquecidos",
    sectors: "Clínicas, imobiliárias, escolas, escritórios e negócios locais",
    domainLevel: 3,
    projectExamples: "",
    results: "",
  },
  niches: [
    {
      id: "niche-clinicas",
      sector: "Clínicas odontológicas",
      experience: "Conheço o fluxo de atendimento e agendamento.",
      access: "Tenho contatos locais e consigo abordar decisores.",
      companySize: "Pequenas e médias",
      mainProblems: "WhatsApp sobrecarregado, perguntas repetidas, leads sem retorno.",
      scores: {
        knowledge: 4,
        access: 4,
        pain: 5,
        urgency: 4,
        ticket: 3,
        recurrence: 4,
      },
    },
    {
      id: "niche-imobiliarias",
      sector: "Imobiliárias",
      experience: "",
      access: "",
      companySize: "Pequenas e médias",
      mainProblems: "Leads de portais e WhatsApp sem acompanhamento.",
      scores: {
        knowledge: 3,
        access: 3,
        pain: 5,
        urgency: 4,
        ticket: 4,
        recurrence: 4,
      },
    },
    {
      id: "niche-escritorios",
      sector: "Escritórios contábeis",
      experience: "",
      access: "",
      companySize: "Pequenas e médias",
      mainProblems: "Documentos espalhados e dúvidas internas repetidas.",
      scores: {
        knowledge: 3,
        access: 2,
        pain: 4,
        urgency: 3,
        ticket: 4,
        recurrence: 5,
      },
    },
  ],
  diagnostics: [
    {
      id: "diag-1",
      area: "Atendimento",
      problem: "Recepção responde as mesmas perguntas todos os dias.",
      currentProcess: "Mensagens chegam pelo WhatsApp e são respondidas manualmente.",
      frequency: 5,
      people: 2,
      hours: 32,
      cost: 1800,
      impact: 4,
      risk: 2,
      urgency: 4,
      automationPotential: 5,
      complexity: 2,
    },
  ],
  services: [
    {
      id: "service-diagnostico",
      name: "Diagnóstico de IA",
      category: "Entrada",
      problem: "A empresa quer usar IA, mas não sabe por onde começar.",
      idealClient: "Empresas com processos manuais e interesse em IA.",
      promisedResult: "Mapa de oportunidades de IA com priorização.",
      deliverables: "Entrevista, mapeamento, análise de oportunidades e recomendação inicial.",
      complexity: "baixa",
      suggestedDeadline: "3 a 5 dias úteis",
      recurringPotential: false,
      priceRange: "R$ 500 a R$ 2.000",
      examples: "Auditoria de WhatsApp, análise de processos internos, mapa de automações.",
    },
    {
      id: "service-atendimento",
      name: "Assistente Inteligente de Atendimento",
      category: "Atendimento",
      problem: "Demora, perguntas repetidas e mensagens perdidas.",
      idealClient: "Clínicas, escolas, restaurantes, lojas e prestadores de serviço.",
      promisedResult: "Atendimento mais rápido e menos trabalho manual.",
      deliverables: "Base de respostas, fluxo, testes, treinamento e ajustes.",
      complexity: "media",
      suggestedDeadline: "10 a 20 dias úteis",
      recurringPotential: true,
      priceRange: "R$ 2.000 a R$ 9.000",
      examples: "FAQ inteligente, triagem, encaminhamento humano e relatórios.",
    },
    {
      id: "service-comercial",
      name: "Assistente Comercial com IA",
      category: "Comercial",
      problem: "Leads entram, mas não são qualificados nem acompanhados.",
      idealClient: "Imobiliárias, escolas, clínicas, consultorias e empresas B2B.",
      promisedResult: "Mais velocidade de resposta e follow-up organizado.",
      deliverables: "Fluxo de qualificação, registro, follow-up e painel simples.",
      complexity: "media",
      suggestedDeadline: "15 a 25 dias úteis",
      recurringPotential: true,
      priceRange: "R$ 3.500 a R$ 15.000",
      examples: "Qualificação de leads, CRM simples, lembretes e agendamento.",
    },
    {
      id: "service-base-conhecimento",
      name: "Base de Conhecimento Inteligente",
      category: "Conhecimento",
      problem: "Informações internas ficam espalhadas e dependem de pessoas específicas.",
      idealClient: "Equipes com manuais, contratos, FAQs, políticas e processos documentados.",
      promisedResult: "Respostas internas rápidas e menor dependência operacional.",
      deliverables: "Organização de documentos, base consultável, testes e treinamento.",
      complexity: "alta",
      suggestedDeadline: "20 a 40 dias úteis",
      recurringPotential: true,
      priceRange: "R$ 5.000 a R$ 20.000+",
      examples: "Cérebro corporativo, busca interna, central de procedimentos.",
    },
  ],
  offer: {
    clientType: "Clínicas odontológicas",
    problem: "mensagens perdidas e perguntas repetidas no WhatsApp",
    result: "melhorar o atendimento e aumentar agendamentos aproveitados",
    solution: "Assistente Inteligente de Atendimento e Agendamento",
    deliverables: "Diagnóstico, base de respostas, fluxo, testes, treinamento e ajustes.",
    deadline: "15 dias úteis",
    investment: 4500,
    recurring: "Plano mensal de suporte e otimização por R$ 890/mês.",
    differentiator: "Foco em problema de negócio, não em ferramenta.",
  },
  pricing: {
    complexity: 3,
    estimatedHours: 32,
    technicalCost: 450,
    toolsCost: 180,
    implementationCost: 900,
    risk: 2,
    maintenance: 6,
    support: 4,
    valueGenerated: 12000,
    savings: 3200,
    revenueUpside: 6000,
    urgency: 4,
  },
  ladder: {
    entry: "Diagnóstico do atendimento pelo WhatsApp - R$ 900",
    initialProject: "FAQ inteligente com triagem inicial - R$ 3.500",
    strategicProject: "Assistente de atendimento e agendamento - R$ 9.500",
    recurrence: "Suporte, melhorias e relatórios - R$ 1.200/mês",
  },
  meeting: {
    client: "Clínica Exemplo",
    status: "agendada",
    context: "Atendimento concentrado no WhatsApp.",
    currentProcess: "Recepção responde manualmente mensagens e dúvidas frequentes.",
    problem: "Demora no retorno e leads esquecidos.",
    problemCost: "Tempo da equipe, perda de agendamentos e experiência ruim.",
    opportunities: "FAQ inteligente, triagem e follow-up.",
    budget: "",
    decisionMakers: "",
    nextSteps: "Agendar diagnóstico de 30 minutos.",
    notes: "",
  },
  proposal: {
    title: "Assistente Inteligente de Atendimento e Agendamento",
    client: "Clínica Exemplo",
    context: "A clínica recebe contatos pelo WhatsApp e Instagram.",
    currentSituation: "A recepção responde dúvidas sobre horários, procedimentos e agenda manualmente.",
    identifiedProblem: "Volume alto de mensagens gera demora, retrabalho e risco de perda de interessados.",
    opportunity: "Automatizar parte do atendimento inicial com IA mantendo encaminhamento humano.",
    solution: "Implantação de assistente inteligente para dúvidas frequentes, triagem e apoio ao agendamento.",
    flow: "Paciente chama -> IA entende -> responde/coleta dados -> encaminha para recepção.",
    scope: "Atendimento inicial, base de respostas, fluxo, testes e treinamento.",
    deliverables: "Diagnóstico, base de respostas, fluxo, configuração, testes, treinamento e ajustes.",
    timeline: "15 dias úteis",
    investment: 4500,
    monthlyPlan: 890,
    conditions: "Ferramentas e custos externos não inclusos, salvo quando especificado.",
    nextSteps: "Aprovar proposta e agendar reunião inicial.",
    status: "rascunho",
  },
  prospects: [
    {
      id: "prospect-1",
      company: "Clínica Exemplo",
      contact: "Mariana",
      niche: "Clínicas odontológicas",
      problem: "WhatsApp sobrecarregado",
      service: "Diagnóstico de IA",
      potentialValue: 4500,
      stage: "identificado",
      nextAction: "Enviar mensagem de diagnóstico",
      date: now.slice(0, 10),
      source: "Rede atual",
      notes: "",
    },
  ],
  implementation: [
    { id: "task-1", label: "Briefing inicial", done: true, owner: "Prestador", dueDate: "", blockers: "" },
    { id: "task-2", label: "Levantamento de perguntas frequentes", done: false, owner: "Cliente", dueDate: "", blockers: "" },
    { id: "task-3", label: "Arquitetura do fluxo", done: false, owner: "Prestador", dueDate: "", blockers: "" },
    { id: "task-4", label: "Configuração e integração", done: false, owner: "Prestador", dueDate: "", blockers: "" },
    { id: "task-5", label: "Testes e validação", done: false, owner: "Ambos", dueDate: "", blockers: "" },
    { id: "task-6", label: "Treinamento e documentação", done: false, owner: "Prestador", dueDate: "", blockers: "" },
  ],
  recurrence: [
    {
      id: "contract-1",
      client: "Clínica Exemplo",
      project: "Assistente de Atendimento",
      monthlyFee: 890,
      monthlyCost: 180,
      dueDay: 10,
      tools: "Automação, WhatsApp, IA",
      improvements: "Ajustes de respostas e relatório mensal.",
      nextReview: now.slice(0, 10),
      renewalDate: "",
    },
  ],
  updatedAt: now,
};

