export const brand = {
  appName: "IA como Serviço",
  ecosystem: "INEMA",
  productLine: "INEMA.PRO",
  tagline: "Da habilidade ao cliente",
  promise:
    "Transforme conhecimento de IA em oferta, diagnóstico, proposta, preço, cliente e recorrência.",
  colors: {
    bg: "#111111",
    surface: "#1a1a1a",
    panel: "#242424",
    panelHigh: "#2b2b2b",
    border: "#333333",
    line: "#242424",
    text: "#ffffff",
    soft: "#dddddd",
    muted: "#bbbbbb",
    dim: "#888888",
    primary: "#FACC15",
    cyan: "#FACC15",
    mint: "#34D399",
    amber: "#FB923C",
    purple: "#60A5FA",
    sky: "#38BDF8",
    rose: "#FB7185",
  },
  radii: {
    sm: "8px",
    md: "8px",
    lg: "8px",
  },
} as const;
